
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

create_clock -period 5.000 -name sysclk_p -waveform {0.000 2.500} [get_ports sysclk_p]
create_clock -period 10.000 -name pcie_clkin_clk_p -waveform {0.000 5.000} [get_ports pcie_clkin_clk_p]

#set_max_delay -to   [get_clocks sysclk_p] -from [get_ports {pcie_reset}] -datapath_only  20.0
#set_min_delay -to   [get_clocks sysclk_p] -from [get_ports {pcie_reset}]  20.0
#set_max_delay -from [get_clocks sysclk_p] -to   [get_ports {ledn[*]}] -datapath_only  20.0
#set_max_delay -from [get_clocks userclk1] -to   [get_ports {qspi_*}] -datapath_only  20.0
#set_max_delay -to   [get_clocks userclk1] -from [get_ports {qspi_*}] -datapath_only  20.0
#set_min_delay -to   [get_clocks userclk1] -from [get_ports {qspi_*}]  20.0

#################

set_property IOSTANDARD LVDS_25 [get_ports sysclk_*]
set_property PACKAGE_PIN J19 [get_ports sysclk_p]
set_property PACKAGE_PIN H19 [get_ports sysclk_n]

set_property PACKAGE_PIN F6 [get_ports {pcie_clkin_clk_p[0]}]
set_property PACKAGE_PIN E6 [get_ports {pcie_clkin_clk_n[0]}]
set_property PACKAGE_PIN G1 [get_ports pcie_clkreq_l]
set_property IOSTANDARD LVCMOS33 [get_ports pcie_clkreq_l]
set_property PACKAGE_PIN J1 [get_ports pcie_reset]
set_property IOSTANDARD LVCMOS33 [get_ports pcie_reset]


set_property IOSTANDARD LVCMOS33 [get_ports {ledn[*]}]
set_property PACKAGE_PIN G3 [get_ports {ledn[0]}]
set_property PACKAGE_PIN H3 [get_ports {ledn[1]}]
set_property PACKAGE_PIN G4 [get_ports {ledn[2]}]
set_property PACKAGE_PIN H4 [get_ports {ledn[3]}]

#set_property IOSTANDARD LVCMOS33    [get_ports {qspi_io*_io}]
#set_property PACKAGE_PIN P22        [get_ports {qspi_io0_io}]
#set_property PACKAGE_PIN R22        [get_ports {qspi_io1_io}]
#set_property PACKAGE_PIN P21        [get_ports {qspi_io2_io}]
#set_property PACKAGE_PIN R21        [get_ports {qspi_io3_io}]
#set_property IOSTANDARD LVCMOS33    [get_ports {qspi_ss_io}]
#set_property PACKAGE_PIN T19        [get_ports {qspi_ss_io}]

set_property PACKAGE_PIN A10 [get_ports {pcie_mgt_rxn[0]}]
set_property PACKAGE_PIN B10 [get_ports {pcie_mgt_rxp[0]}]
set_property PACKAGE_PIN A6 [get_ports {pcie_mgt_txn[0]}]
set_property PACKAGE_PIN B6 [get_ports {pcie_mgt_txp[0]}]
set_property PACKAGE_PIN A8 [get_ports {pcie_mgt_rxn[1]}]
set_property PACKAGE_PIN B8 [get_ports {pcie_mgt_rxp[1]}]
set_property PACKAGE_PIN A4 [get_ports {pcie_mgt_txn[1]}]
set_property PACKAGE_PIN B4 [get_ports {pcie_mgt_txp[1]}]
set_property PACKAGE_PIN C9 [get_ports {pcie_mgt_rxn[3]}]
set_property PACKAGE_PIN D9 [get_ports {pcie_mgt_rxp[3]}]
set_property PACKAGE_PIN C7 [get_ports {pcie_mgt_txn[3]}]
set_property PACKAGE_PIN D7 [get_ports {pcie_mgt_txp[3]}]



connect_debug_port u_ila_0/probe0 [get_nets [list {bram_addr_counter_sig[2]} {bram_addr_counter_sig[3]} {bram_addr_counter_sig[4]} {bram_addr_counter_sig[5]} {bram_addr_counter_sig[6]} {bram_addr_counter_sig[7]} {bram_addr_counter_sig[8]} {bram_addr_counter_sig[9]} {bram_addr_counter_sig[10]} {bram_addr_counter_sig[11]} {bram_addr_counter_sig[12]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {next_state_sig[0]} {next_state_sig[1]} {next_state_sig[2]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {usr_irq_req[0]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list acq_ctrl_rst_n_sig]]
connect_debug_port u_ila_0/probe5 [get_nets [list buffer_full_sig]]
connect_debug_port u_ila_0/probe6 [get_nets [list irq_pending_sig_synced]]
connect_debug_port dbg_hub/clk [get_nets clk]


set_property MARK_DEBUG true [get_nets {usr_irq_ack_sig_sycend[0]}]
set_property MARK_DEBUG true [get_nets {mem_addr_out_sig[1]}]
set_property MARK_DEBUG true [get_nets {mem_addr_out_sig[3]}]
set_property MARK_DEBUG true [get_nets {mem_addr_out_sig[6]}]
set_property MARK_DEBUG true [get_nets {mem_addr_out_sig[11]}]
set_property MARK_DEBUG true [get_nets is_running_sig]
set_property MARK_DEBUG true [get_nets enable_acquisition_synced]
set_property MARK_DEBUG true [get_nets soft_rst_pci_rst_sig]
set_property MARK_DEBUG true [get_nets {mem_addr_out_sig[4]}]
set_property MARK_DEBUG true [get_nets {mem_addr_out_sig[0]}]
set_property MARK_DEBUG true [get_nets {mem_addr_out_sig[2]}]
set_property MARK_DEBUG true [get_nets {mem_addr_out_sig[5]}]
set_property MARK_DEBUG true [get_nets {mem_addr_out_sig[9]}]
set_property MARK_DEBUG true [get_nets {mem_addr_out_sig[10]}]
set_property MARK_DEBUG true [get_nets {mem_addr_out_sig[12]}]
set_property MARK_DEBUG true [get_nets irq_pending_B_sig_synced]
set_property MARK_DEBUG true [get_nets irq_pending_A_sig_synced]
set_property MARK_DEBUG true [get_nets ready_B_sig]
set_property MARK_DEBUG true [get_nets sys_clk]
set_property MARK_DEBUG true [get_nets ping_pong_we_sig]
set_property MARK_DEBUG true [get_nets ready_A_sig]
set_property MARK_DEBUG true [get_nets sample_valid_sig]
set_property MARK_DEBUG true [get_nets {mem_addr_out_sig[7]}]
set_property MARK_DEBUG true [get_nets {mem_addr_out_sig[8]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[0]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[1]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[2]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[3]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[4]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[5]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[6]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[7]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[8]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[9]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[10]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[11]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[12]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[13]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[14]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[15]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[16]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[17]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[18]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[19]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[20]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[21]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[22]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[23]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[24]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[25]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[26]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[27]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[28]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[29]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[30]}]
set_property MARK_DEBUG true [get_nets {BRAM_PORTB_0_din_sig[31]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[16]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[30]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[3]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[4]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[7]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[22]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[24]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[14]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[5]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/current_addr_sig_reg[10]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/current_addr_sig_reg[12]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[20]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[11]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[8]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/current_addr_sig_reg[2]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[15]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[23]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[25]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[17]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[26]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[9]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/current_addr_sig_reg[1]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/current_addr_sig_reg[8]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/current_addr_sig_reg[11]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[10]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[12]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[28]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[18]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/current_addr_sig_reg[3]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/current_addr_sig_reg[4]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/current_addr_sig_reg[6]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[19]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[21]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[13]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[0]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[1]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[6]}]
set_property MARK_DEBUG true [get_nets ping_pong_ctrl_inst/ready_B_sig]
set_property MARK_DEBUG true [get_nets ping_pong_ctrl_inst/ready_A_sig]
set_property MARK_DEBUG true [get_nets ping_pong_ctrl_inst/sample_valid_sig]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[31]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[2]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/current_addr_sig_reg[0]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/current_addr_sig_reg[5]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/current_addr_sig_reg[9]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[27]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/mem_data_out_reg[31]_0[29]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/BRAM_PORTB_0_we[0]}]
set_property MARK_DEBUG true [get_nets {ping_pong_ctrl_inst/current_addr_sig_reg[7]}]
connect_debug_port u_ila_0/clk [get_nets [list sys_clk_BUFG]]
connect_debug_port u_ila_0/probe2 [get_nets [list {block_design_inst/BRAM_PORTB_0_we[0]}]]
connect_debug_port dbg_hub/clk [get_nets sys_clk_BUFG]




connect_debug_port u_ila_0/probe5 [get_nets [list usr_irq_req_A_sig]]
connect_debug_port u_ila_0/probe6 [get_nets [list usr_irq_req_B_sig]]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list sys_clk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 11 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {irq_a_cnt_sig[0]} {irq_a_cnt_sig[1]} {irq_a_cnt_sig[2]} {irq_a_cnt_sig[3]} {irq_a_cnt_sig[4]} {irq_a_cnt_sig[5]} {irq_a_cnt_sig[6]} {irq_a_cnt_sig[7]} {irq_a_cnt_sig[8]} {irq_a_cnt_sig[9]} {irq_a_cnt_sig[10]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 3 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {next_state_B_sig[0]} {next_state_B_sig[1]} {next_state_B_sig[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {usr_irq_req_sig[0]} {usr_irq_req_sig[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {ready_a_cnt_sig[0]} {ready_a_cnt_sig[1]} {ready_a_cnt_sig[2]} {ready_a_cnt_sig[3]} {ready_a_cnt_sig[4]} {ready_a_cnt_sig[5]} {ready_a_cnt_sig[6]} {ready_a_cnt_sig[7]} {ready_a_cnt_sig[8]} {ready_a_cnt_sig[9]} {ready_a_cnt_sig[10]} {ready_a_cnt_sig[11]} {ready_a_cnt_sig[12]} {ready_a_cnt_sig[13]} {ready_a_cnt_sig[14]} {ready_a_cnt_sig[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 3 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {next_state_A_sig[0]} {next_state_A_sig[1]} {next_state_A_sig[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 11 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {irq_b_cnt_sig[0]} {irq_b_cnt_sig[1]} {irq_b_cnt_sig[2]} {irq_b_cnt_sig[3]} {irq_b_cnt_sig[4]} {irq_b_cnt_sig[5]} {irq_b_cnt_sig[6]} {irq_b_cnt_sig[7]} {irq_b_cnt_sig[8]} {irq_b_cnt_sig[9]} {irq_b_cnt_sig[10]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 16 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {ready_b_cnt_sig[0]} {ready_b_cnt_sig[1]} {ready_b_cnt_sig[2]} {ready_b_cnt_sig[3]} {ready_b_cnt_sig[4]} {ready_b_cnt_sig[5]} {ready_b_cnt_sig[6]} {ready_b_cnt_sig[7]} {ready_b_cnt_sig[8]} {ready_b_cnt_sig[9]} {ready_b_cnt_sig[10]} {ready_b_cnt_sig[11]} {ready_b_cnt_sig[12]} {ready_b_cnt_sig[13]} {ready_b_cnt_sig[14]} {ready_b_cnt_sig[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list usr_irq_ack_A_sig]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list usr_irq_ack_B_sig]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sys_clk]
